## Write a function that creates an Alexandre Theophile Vandermonde matrix.

Specific instructions:
1. create a function
2. including an increasing boolean argument
2.1. if increasing = False, then ith column = i**(N-i-1), else opposite is true.
2.2. need a vector to be supplied as x


Note: completion requires showing detailed steps used to create the this function.  Assume this means do not use built in numpy function.  This is unclear so I will submit multiple solution approaches.

In [1]:
import numpy as np

In [2]:
def main():
    """Calls functions to create desired Vandermonde matrix."""
    result = 0
    vector_list = [1, 2, 7, 10, 20, 100]
    number_of_columns = 3
    increasing_by_power = True
    result = calculate_matrix(vector_list, number_of_columns, increasing_by_power)
    result_formatted = create_formatted_array(result)
    result_of_test = test_results(vector_list, number_of_columns, increasing_by_power)
    return result_formatted, result_of_test

def create_formatted_array(vector_lists): return np.column_stack(vector_lists)    

def calculate_increasing_matrix(vector_list, number_of_columns):
    """Calculate a matrix based on power increasing by 1 with the number of columns"""
    calculated_vector_list = []
    calculated_column = []
    power_without_column_number = number_of_columns
    for column_number in range(number_of_columns, 0, -1):
        for vector in vector_list:
            power_multiple = (power_without_column_number - column_number)
            vector_power_value = vector ** power_multiple
            calculated_column.append(vector_power_value)
        calculated_vector_list.append(calculated_column)
        calculated_column = []
    return calculated_vector_list

def calculate_decreasing_matrix(vector_list, number_of_columns):
    """Calculate a matrix based on power decreasing by 1 with the number of columns"""
    calculated_vector_list = []
    calculated_column = []
    power_without_column_number = number_of_columns - 1
    for column_number in range(number_of_columns):
        for vector in vector_list:
            vector_power_value = vector ** (power_without_column_number - column_number)
            calculated_column.append(vector_power_value)
        calculated_vector_list.append(calculated_column)
        calculated_column = []
    return calculated_vector_list

def calculate_matrix(vector_list, number_of_columns, increasing_by_power):
    """Calculate a matrix where a vector is increased by the current column value."""
    if increasing_by_power == True:
        result_increasing = calculate_increasing_matrix(vector_list, number_of_columns)
        return result_increasing
    elif increasing_by_power == False:
        result_decreasing = calculate_decreasing_matrix(vector_list, number_of_columns)
        return result_decreasing
    else:
        print('There is a problem.')

def test_results(vector_list, number_of_columns, increasing_by_power):
    vector = np.array(vector_list)
    test_output = np.vander(vector, N=number_of_columns, increasing=increasing_by_power)
    return test_output

In [3]:
if __name__ == "__main__":
    final_matrix, test_matrix = main()
    print('Here is the Vander matrix created by this program:')
    print(final_matrix)
    print('\n')
    print("Here is the Vander matrix created by numpy's built in function:")
    print(test_matrix)

Here is the Vander matrix created by this program:
[[    1     1     1]
 [    1     2     4]
 [    1     7    49]
 [    1    10   100]
 [    1    20   400]
 [    1   100 10000]]


Here is the Vander matrix created by numpy's built in function:
[[    1     1     1]
 [    1     2     4]
 [    1     7    49]
 [    1    10   100]
 [    1    20   400]
 [    1   100 10000]]
